### ISSUE TITLE
(Sugestão) Mais parâmetros de busca

### ISSUE THREAD

**Issue by Mazuh** [rafpyprog/ImageSoup#1]
O Google permite vários parâmetros na busca das imagens. Especificamente eu tô pensando em algo a ver com as dimensões da imagem. Digamos que meu sistema esteja em busca de wallpapers, então eu queria colocar um tamanho mais específico de imagens ou (se possível) um intervalo de tamanhos (como max-width, min-width, etc).

Pretendo implementar uma função num sistema e esse recurso viria a calhar. Se der certo eu até te aviso (vai estar no Github, anyway).

**Comment by rafpyprog** [comment]
Solved on [release 0.0.10](https://github.com/rafpyprog/ImageSoup/releases/tag/v0.0.10). Upgrade your package version using pip.
